### ISSUE TITLE
Bugs with: LogIn / Register / Add to Cart / Like Product / Show Product / WishList .....

### ISSUE THREAD

**Issue by BonBonSlick** [ant-vel/antVel#202] opened 2016-10-17 15:33 UTC
--- When press **add to cart or like product / wishlist / your wishlist / ** i have this error:
FatalErrorException in Handler.php line 135:
Call to undefined method App\Exceptions\Handler::unauthenticated()
in Handler.php line 135

-- When clicking on product ( thumbnail / name link / or button link to see more info ):
ErrorException in 435dc909906be573862abbd30f4fdf4ff352d505.php line 139:
Trying to get property of non-object (View: C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\resources\views\products\detailProd.blade.php)
in 435dc909906be573862abbd30f4fdf4ff352d505.php line 139
at CompilerEngine->handleViewException(object(ErrorException), '0') in PhpEngine.php line 44
at PhpEngine-.......

-- When logining ( captcha works ):
BadMethodCallException in Controller.php line 82:
Method [getFailedLoginMessage] does not exist.
in Controller.php line 82
at Controller->__call('getFailedLoginMessage', array()) in LoginController.php line 75...

And other bugs.....

**Comment by gocanto** [comment] 2016-10-17 15:34
what other bugs? can u be more clear? 

thanks

**Comment by BonBonSlick** [comment] 2016-10-17 16:04
I have done all as it said. So, i have web site, working Data Base, .env is seems to be okay. Captcha and map connected.  Also, i am using Windows 7/ OpenServer ( PhP 5.6 - MySQL 5.7, Apache 2.4, bower and other dependencies installed ). 
Every feature i found, will use ---

**--- click 'Add to cart' button ( where it is ).** 
FatalErrorException in Handler.php line 135:
Call to undefined method App\Exceptions\Handler::unauthenticated()
in Handler.php line 135

**-- click 'Like' the product ( heart shape button ):**
FatalErrorException in Handler.php line 135:
Call to undefined method App\Exceptions\Handler::unauthenticated()
in Handler.php line 135

**--- click 'Product info' ( aye button / name link / img ( thumbnail )  ):**
ErrorException in 435dc909906be573862abbd30f4fdf4ff352d505.php line 139:
Trying to get property of non-object (View: C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\resources\views\products\detailProd.blade.php)
in 435dc909906be573862abbd30f4fdf4ff352d505.php line 139
at CompilerEngine->handleViewException(object(ErrorException), '0') in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\storage\framework\views/435dc909906be573862abbd30f4fdf4ff352d505.php', array('__env' => object(Factory), 'app' => object(Application), 'main_company' => object(Company), 'categories_menu' => array(array('id' => '1', 'name' => 'Digital & Music'), array('id' => '14', 'name' => 'Books & Audible'), array('id' => '30', 'name' => 'Movies, Music & Games'), array('id' => '58', 'name' => 'Electronics & Computers'), array('id' => '113', 'name' => 'Home, Garden & Tools'), array('id' => '156', 'name' => 'Beauty, Health & Grocery'), array('id' => '181', 'name' => 'Toys, Kids & Baby'), array('id' => '206', 'name' => 'Clothing, Shoes & Jewelry'), array('id' => '225', 'name' => 'Sports & Outdoors'), array('id' => '280', 'name' => 'Automotive & Industrial'), array('id' => '308', 'name' => 'Home Services')), 'errors' => object(ViewErrorBag), 'product' => object(Product), 'panel' => array('center' => array('width' => '12')), 'allWishes' => '', 'reviews' => object(Collection), 'freeproductId' => '0', 'features' => array(array('id' => '1', 'name' => 'images', 'input_type' => 'image', 'default_values' => '{}', 'validation_rules' => '{"images_1": .....

**---  click 'wishlist' dropdown button:**
FatalErrorException in Handler.php line 135:
Call to undefined method App\Exceptions\Handler::unauthenticated()
in Handler.php line 135

**--- click 'Your wishlist':**
FatalErrorException in Handler.php line 135:
Call to undefined method App\Exceptions\Handler::unauthenticated()
in Handler.php line 135
============================================
( account register works fine, so when i registered there are no such errors).
============================================
Now i will try do some sort of things logged as new registered user.

**--- i cant upload avatar, when i click 'Update Profile', there is error ( with updating other info same things ):**
The E-Mail has already been taken.
The User Name (Nickname) has already been taken.

Okay, now gonna try as **admin**.

**--- i logged as admin, when captcha is not checked**

**--- 'Notice' page unclickable.  I think even if it is empty, i need some message.** 

**WEB PANEL**

-- click 'store settings ':
ErrorException in UrlGenerator.php line 314:
Route [wpanel.profile.update] not defined. (View: C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\resources\views\company\index.blade.php)
in UrlGenerator.php line 314
at CompilerEngine->handleViewException(object(InvalidArgumentException), '0') in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\storage\framework\views/06c942be95be623be070da89e93996eb2cd52304.php', array('__env' => object(Factory), 'app' => object(Application), 'main_company' => object(Company), 'categories_menu' => array(array('id' => '1', 'name' => 'Digital & Music'), array('id' => '14', 'name' => 'Books & Audible'), array('id' => '30', 'name' => 'Movies, Music & Games'), array('id' => '58', 'name' => 'Electronics & Computers'), array('id' => '113', 'name' => 'Home, Garden & Tools'), array('id' => '156', 'name' => 'Beauty, Health & Grocery'), array('id' => '181', 'name' => 'Toys, Kids & Baby'), array('id' => '206', 'name' => 'Clothing, Shoes & Jewelry'), array('id' => '225', 'name' => 'Sports & Outdoors'), array('id' => '280', 'name' => 'Automotive & Industrial'), array('id' => '308', 'name' => 'Home Services')), 'errors' => object(ViewErrorBag), 'panel' => array('left' => array('width' => '2'), 'center' => array('width' => '10')), 'company' => object(Company))) in CompilerEngine.php line 59
at CompilerEngine->get('C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\resources\views/company/index.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'main_company' => object(Company), 'categories_menu' => array(array('id' => '1', 'name' => 'Digital & Music'), array('id' => '14', 'name' => 'Books & Audible'), array('id' => '30', 'name' => 'Movies, Music & Games'), array('id' => '58', 'name' => 'Electronics & Computers'), array('id' => '113', 'name' => 'Home, Garden & Tools'), array('id' => '156', 'name' => 'Beauty, Health & Grocery'), array('id' => '181', 'name' => 'Toys, Kids & Baby'), array('id' => '206', 'name' => 'Clothing, Shoes & Jewelry'), array('id' => '225', 'name' => 'Sports & Outdoors'), array('id' => '280', 'name' => 'Automotive & Industrial'), array('id' => '308', 'name' => 'Home Services')), 'errors' => object(ViewErrorBag), 'panel' => array('left' => array('width' => '2'), 'center' => array('width' => '10')), 'company' => object(Company))) in View.php line 149.........
...

**--- 'Product Category' page, when i clicked:**
ErrorException in UrlGenerator.php line 314:
Route [wpanel.category.create] not defined. (View: C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\resources\views\categories\home.blade.php)
in UrlGenerator.php line 314
at CompilerEngine->handleViewException(object(InvalidArgumentException), '0') in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\storage\framework\views/484724333e6d2fc6f6d8928c265d0f93335aca58.php', array('__env' => object(Factory), 'app' => object(Application), 'main_company' => object(Company), 'categories_menu' => array(array('id' => '1', 'name' => 'Digital & Music'), array('id' => '14', 'name' => 'Books & Audible'), array('id' => '30', 'name' => 'Movies, Music & Games'), array('id' => '58', 'name' => 'Electronics & Computers'), array('id' => '113', 'name' => 'Home, Garden & Tools'), array('id' => '156', 'name' => 'Beauty, Health & Grocery'), array('id' => '181', 'name' => 'Toys, Kids & Baby'), array('id' => '206', 'name' => 'Clothing, Shoes & Jewelry'), array('id' => '225', 'name' => 'Sports & Outdoors'), array('id' => '280', 'name' => 'Automotive & Industrial'), array('id' => '308', 'name' => 'Home Services')), 'errors' => object(ViewErrorBag), 'categories' => object(Categories), 'panel' => array('left' => array('width' => '2'), 'center' => array('width' => '10')))) in CompilerEngine.php line 59.....

**-- And last one, 'Product Features' page, click:**
ErrorException in UrlGenerator.php line 314:
Route [wpanel.productsdetails.create] not defined. (View: C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\resources\views\features\index.blade.php)
in UrlGenerator.php line 314
at CompilerEngine->handleViewException(object(InvalidArgumentException), '0') in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\Users\BonBonS\Desktop\OpenServer\domains\antvel\storage\framework\views/f5b8397a8f1f6bc309068ed13c8a7253b41a34d6.php', array('__env' => object(Factory), 'app' => object(Application), 'main_company' => object(Company), 'categories_menu' => array(array('id' => '1', 'name' => 'Digital & Music'), array('id' => '14', 'name' => 'Books & Audible'), array('id' => '30', 'name' => 'Movies, Music & Games'), array('id' => '58', 'name' => 'Electronics & Computers'), array('id' => '113', 'name' => 'Home, Garden & Tools'), array('id' => '156', 'name' => 'Beauty, Health & Grocery'), array('id' => '181', 'name' => 'Toys, Kids & Baby'), array('id' => '206', 'name' => 'Clothing, Shoes & Jewelry'), array('id' => '225', 'name' => 'Sports & Outdoors'), array('id' => '280', 'name' => 'Automotive & Industrial'), array('id' => '308', 'name' => 'Home Services')), 'errors' => object(ViewErrorBag), 'panel' => array('left' => array('width' => '2'), 'center' => array('width' => '10')), 'features' => object(Collection))) in CompilerEngine.php line 59...


I am sure, there are a lot of more, but i am gonna to develope my own web market with laravel ( i am newbie ), while searching for inspiring open source project, to look through the code.

**Comment by gocanto** [comment] 2016-10-17 16:06
Ok thanks, I will look into it

**Comment by Artessan** [comment] 2016-10-17 19:58
The problem is the authentication, for add product to cart or wishlist is required be authenticated, the bottons need to be disabled or invisible for not authenticated users.

**Comment by BonBonSlick** [comment] 2016-10-18 10:36
I know, but for common users maybe author should add some redirect, or error message. Also, adminpanel, we cant manage our site, add / delete / edit - users / products / categories and roles.

**Comment by Artessan** [comment] 2016-10-18 13:41
Of course in the future is comtemplated add an admin area for manager all this things.

**Comment by gocanto** [comment] 2016-10-18 13:50
We are working on the ecommerce refactoring. We are gonna get look into this bugs in order for all of you can use the site as it is. New features, validation, etc will be shipped whithin the new version. 

Again, thanks for testing.

**Comment by gocanto** [comment] 2016-10-18 19:07
Fixed on PR #204 by @Artessan 

Let us know how it goes

**Closed by gocanto** 2016-10-18 19:07 UTC
Labels: bug

**Comment by BonBonSlick** [comment] 2016-10-23 12:47
Ok, i have checked, and found again couple bugs. ( cleared all cache, created new DB, folder, generally started as new project ).

**---=== I logged when captcha check failed, or even not checked.**

**---=== I there is no such user, i have got laravel error page in Countroller...**:

**---=== Also, when i clicked aye to see product i have:**
ErrorException in f1b922fe9942d15a44de32dd6886e4bfb39a1873.php line 139:
Trying to get property of non-object (View: C:\Users\BonBonS\Desktop\OpenServer\domains\antvel2\resources\views\products\detailProd.blade.php)...
...at CompilerEngine->handleViewException(object(ErrorException), '0') in PhpEngine.php line 44
at PhpEngine-....

**---=== Other one, idk why, after first login, i cant log in or sign out, i have ( sometimes this error )**:
Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated.....
I am sure, there is more, but here i supposed to stop, will be waiting for new patches, and will try it maybe in couple weeks. 
U've done great work, but it is still not enough to start it working  well. =(

**Comment by BonBonSlick** [comment] 2016-10-23 12:51
Artessan, i always prefer to start new website from adminpanel building, to see what will be siplayed on front, how admins / moders can manage   data and etc important things.

**Comment by gocanto** [comment] 2016-10-23 13:16
Hi, thanks for your feedback. We will look into them as soon as possible. In the meanwhile, you are free to send PR's if you would like to contribute. This project was a testing one for me, but now, we are working on its refactoring ant-vel/Shop. 

We will try to have this done asap. 

Thanks
