### ISSUE TITLE
Strange issue while making new product

### ISSUE THREAD

**Issue by TsenkoTsenov** [ant-vel/antVel#156] opened 2016-06-27 20:35 UTC
Hey so, when i tried to create new product got this:
![4](https://cloud.githubusercontent.com/assets/12273257/16394512/4a0082d2-3cbe-11e6-9f16-68a4d6a42325.png)
So i opened the editor played for a while and after changing this block of code:
![6](https://cloud.githubusercontent.com/assets/12273257/16394523/5ac7f316-3cbe-11e6-9122-d093436df1d2.png)
_( The strange thing is that this key/value pair syntax is absolutely valid )_
TO:
![1](https://cloud.githubusercontent.com/assets/12273257/16394526/5da61f22-3cbe-11e6-8535-074377bdb178.png)
For some strange reason it worked:
![2](https://cloud.githubusercontent.com/assets/12273257/16394535/680a44b6-3cbe-11e6-941c-a8bc065544bc.png)
_( With some mess with the new lines )_

**Comment by gocanto** [comment] 2016-06-27 20:37
well, this is very wired because I just tested it and i worked fine locally.. I ll give it a look

**Comment by TsenkoTsenov** [comment] 2016-06-27 21:08
Hey i forgot to say that this second _foreach_ that i applied works ONLY when creating new products, but when i go in catalog and try to see some product it breaks to this:
![6](https://cloud.githubusercontent.com/assets/12273257/16395655/bf1f4616-3cc3-11e6-9544-030adfc8e721.png)]

**Comment by TsenkoTsenov** [comment] 2016-06-27 21:13
Actually with this second foreach i can browse and see only products created by the seller account ( not seeded )

**Comment by riverrun46** [comment] 2016-06-28 02:50
This is because each feature is assumed to return a string, but instead it returns a array like this:
`Dimensions: ['blablabla', '']`

I think the problem is in function _validateFeatures()_, which is called when storing or updating a product. 

```
if ($row['help_message'] != '' && (strpos('video image document', $row['input_type']) === false)) {
                    $message = '';
                    if (isset($row['helpMessageArray']['general'])) {
                        $message = $row['helpMessageArray']['general'];
                    } elseif (isset($row['helpMessageArray']['general_selection'])) {
                        $message = $data['help_msg_'.$row['indexByName']];
                    }
                    $values = [$data['feature_'.$row['indexByName']], $message];
                } else {
                    $values = $data['feature_'.$row['indexByName']];
                }
```
Notice the if statement in the first line is like `if ($row['help_message'] != '')`, but the _help_message_ column of each productdetails is actually seeded like this:

```
// ProductsDetailTableSeeder.php

        ProductDetail::create([
            'name'             => 'virtual weight',
            'input_type'       => 'text',
             'status'          => 'active',
            'default_values'   => '{}',
            'validation_rules' => '{}',
            'help_message'     => '{}',
            'type_products'    => 'key',
            'max_num_values'   => 1,
        ]);

```

so the if statement here returns a TRUE, while we expect it to be a FALSE. So each values of features returns a 2-list like `$values = [$data['feature_'.$row['indexByName']], $message];` istead of the data only. That result in the failure of function `ucwords()` in the blade template file.

**Comment by gocanto** [comment] 2016-06-28 14:39
I will do a deed check because for some reason everything is bad. Those erros are not in the demo page and I need to find out what's goong on

**Comment by gocanto** [comment] 2016-06-28 15:19
I just merged a fix for this issue to ```development``` branch. Please, check if resolved your problem. 

Commit: https://github.com/ant-vel/antVel/commit/044dad27baaeeb3d55d3a1e9dd4d71a65fa02c8c

thanks for testing!

**Comment by TsenkoTsenov** [comment] 2016-06-28 18:31
Yes, it works great now!

**Closed** 2016-06-28 18:33 UTC
Labels: bug
