### ISSUE TITLE
The last issue i found - Password reset issue

### ISSUE THREAD

**Issue by TsenkoTsenov** [ant-vel/antVel#166] opened 2016-07-08 11:04 UTC
Hello, so i think i got through all the features. I got only problem with the password reset.
Locally when i try to password reset:
![12](https://cloud.githubusercontent.com/assets/12273257/16685567/a1ba1246-4514-11e6-88fd-042b44b1b6ac.png)
Right after clicking "Password Reset" it pops out this one:
![212](https://cloud.githubusercontent.com/assets/12273257/16685574/aa08201e-4514-11e6-8321-cab859c07d6a.png)
But on your hosted antvel.com site, i got further for some reason and recieved the email. But when i clicked the link got this: 
![2342344](https://cloud.githubusercontent.com/assets/12273257/16685589/bf9fdf5c-4514-11e6-84eb-1fad5a0978f0.png)

**Comment by TsenkoTsenov** [comment] 2016-07-08 11:55
Oh okay, found the solution to the both issues. Created new folder named "emails" in views/auth/ and moved password.blade.php ( previously located in views/emails ) to it. Then removed "MARKEDFORDELETION" thing in reset.blade.php located in "views/auth"  and it worked.

**Comment by gocanto** [comment] 2016-07-08 15:46
I gotta take a look at it.. I have been busy latelly tho

On 7/8/16, Tsenko Tsenov <notifications@github.com> wrote:
> Oh okay, found the solution to the both issues. Created new folder named
> "emails" in views/auth/ and moved password.blade.php ( previously located in
> views/emails ) to it. Then removed "MARKEDFORDELETION" thing in
> reset.blade.php located in "views/auth"  and it worked.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ant-vel/antVel/issues/166#issuecomment-231341502


-- 




*Antes de imprimir este e-mail piense bien si es necesario hacerlo, cuida
tu ambiente.*

*NOTA CONFIDENCIAL: La información contenida en este E-mail es confidencial
y sólo puede ser utilizada por la persona o la compañía a la cual está
dirigido y/o por el emisor. Si no es el receptor autorizado, cualquier
retención, difusión, distribución o copia de este mensaje es prohibida y
será sancionada por la ley. Si por error recibe este mensaje, favor
devolverlo y borrar el mensaje recibido inmediatamente.*

CONFIDENTIAL NOTE: The information in this E-mail is intended to be
confidential and only for use of the individual or entity to whom it is
addressed and/or the issuer. If you are not the intended recipient, any
retention, dissemination, distribution or copying of this message is
strictly prohibited and sanctioned by law. If you receive this message by
error, please immediately send it back and delete the message received.

**Comment by beshambher** [comment] 2016-07-29 09:06
Yes I'm having the same issue the problem is with the view it send to the user in email. I have password.blade in views/emails/ which holds the password reset link but it cannot be used in the Mail that is sent to the user instead of that it is sending views/auth/reset.blade in the mail.

**Comment by beshambher** [comment] 2016-07-29 09:12
If you want some help in removing bugs from AntVel then I can help u in back-end part but I don't know anything about Angular JS.

**Comment by gocanto** [comment] 2016-07-29 12:38
Yes please, i need help. PR are very welcome

**Comment by gocanto** [comment] 2016-07-29 14:46
Btw, I am waiting on Lravel 5.3 because I think the best way to go is rewriting!

**Comment by beshambher** [comment] 2016-08-01 13:24
No need to re-write, it will take forever. Debugging the existing code is fine.

**Comment by gocanto** [comment] 2016-08-01 15:45
Checking these bugs is taking me forever. I need help! when I wrote this project I had a lot of time, fact that is not the same now 👎

**Comment by beshambher** [comment] 2016-08-02 14:10
Ohh then what you suggest now?

**Comment by gocanto** [comment] 2016-08-02 20:41
I am planning whit a little group the bugs checking and the backend rewritting, so whoever wants to jomp in should drop his email in here!

**Comment by beshambher** [comment] 2016-08-03 07:34
here bishamberc@gmail.com

**Comment by saadj55** [comment] 2016-08-03 08:38
add me saadj55@gmail.com

**Comment by gocanto** [comment] 2016-08-03 13:52
I will be adding you all in the antvel slack channel today. Thanks a lot

**Comment by gocanto** [comment] 2016-08-08 15:11
I had texted you in slack and haven't get any response from you all at all

**Comment by beshambher** [comment] 2016-08-09 05:17
Sorry I thought I'll get a mail also from stack as notifications so sorry.

**Comment by napestershine** [comment] 2016-08-30 09:31
napestershine@gmail.com add me

**Comment by gocanto** [comment] 2016-09-02 19:18
Fixed on #195

**Closed by gocanto** 2016-09-02 19:18 UTC
